# -*- coding: utf-8 -*-
"""speech_recognition.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Bnh72oZrE1RoebBhf_YkhJa66full8o5
"""

#speech recognition using python

import speech_recognition as sr
import webbrowser as wb
from gtts import gTTS
import os
import numpy as np
import matplotlib.pyplot as plt
import sys

r = sr.Recognizer()
url = 'https://www.google.com/search?query='
with sr.Microphone() as source:
    print("\nSearch the web :- ")
    audio = r.listen(source)
try:
    text = r.recognize_google(audio)
    tts = gTTS(text, 'de')
    tts.save('hello.m4a')
    os.system("start hello.m4a")
    print('you said : {}'.format(text))
    wb.get().open_new(url+text)
except:
    print("Sorry could not recognize what you said")

